<?php

namespace ContainerQc3SQS5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTipsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\Forebet\Tips' shared autowired service.
     *
     * @return \App\Command\Forebet\Tips
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/Forebet/Tips.php';

        $container->privates['App\\Command\\Forebet\\Tips'] = $instance = new \App\Command\Forebet\Tips(($container->privates['App\\Repository\\ForebetRepository'] ?? $container->load('getForebetRepositoryService')), ($container->privates['App\\Repository\\ForebetOptimalValuesRepository'] ?? $container->load('getForebetOptimalValuesRepositoryService')));

        $instance->setName('forebet:tips');

        return $instance;
    }
}
