<?php

namespace ContainerNf7UqyX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImportService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\Forebet\Import' shared autowired service.
     *
     * @return \App\Command\Forebet\Import
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/Forebet/Import.php';
        include_once \dirname(__DIR__, 4).'/src/Tipster/ForeBet.php';
        include_once \dirname(__DIR__, 4).'/src/Service/FilesystemService.php';

        $container->privates['App\\Command\\Forebet\\Import'] = $instance = new \App\Command\Forebet\Import(new \App\Tipster\ForeBet(($container->privates['App\\Repository\\ForebetRepository'] ?? $container->load('getForebetRepositoryService')), new \App\Service\FilesystemService()));

        $instance->setName('forebet:import');

        return $instance;
    }
}
