<?php

namespace ContainerNf7UqyX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReportService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\Forebet\Report' shared autowired service.
     *
     * @return \App\Command\Forebet\Report
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/Forebet/Report.php';

        $container->privates['App\\Command\\Forebet\\Report'] = $instance = new \App\Command\Forebet\Report(($container->privates['App\\Repository\\ForebetRepository'] ?? $container->load('getForebetRepositoryService')));

        $instance->setName('forebet:report');

        return $instance;
    }
}
