<?php

namespace Container3TkIVjY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImport2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\TodayFootballPrediction\Import' shared autowired service.
     *
     * @return \App\Command\TodayFootballPrediction\Import
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/TodayFootballPrediction/Import.php';

        $container->privates['App\\Command\\TodayFootballPrediction\\Import'] = $instance = new \App\Command\TodayFootballPrediction\Import();

        $instance->setName('todayfootballprediction:import');

        return $instance;
    }
}
