<?php

namespace ContainerIDf2nLt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSureBetsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\Forebet\SureBets' shared autowired service.
     *
     * @return \App\Command\Forebet\SureBets
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/Forebet/SureBets.php';

        $container->privates['App\\Command\\Forebet\\SureBets'] = $instance = new \App\Command\Forebet\SureBets();

        $instance->setName('sure:bets');

        return $instance;
    }
}
